spring:
  datasource:
    url: jdbc:mysql://localhost:3306/srping-boot-test?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  messages:
    encoding: UTF-8
    basename: messages